"""
One file that says which compartments exist, what material feeds each one,
and which cluster it belongs to. One command that builds all of it.

Before this, laying out a corpus for a company with forty departments meant
somebody writing a script. That script lived on their laptop, nobody else
could re-run it, and the folder layout, the access policy and the family
grouping were three separate hand edits that could disagree with each other
without anyone noticing.

So the three become one file. The plan names each compartment once and
carries everything about it in the same place.

    compartments:
      engineering:
        tier: department
        family: technical
        folders: [raw/engineering]
        urls:    [https://...]

Putting the family on the compartment rather than in a separate list is not
a style choice. A compartment must belong to exactly one family, because the
family decides which adapter carries its language. Written this way that
rule holds by construction and there is nothing to check.

The build then produces the folder layout, the access policy and the family
spec together, from the single source, so they cannot drift apart.

What this deliberately does not do is guess. A compartment with no material
is an error, not an empty folder. A folder that does not exist is an error,
not a warning. A plan that would produce an access policy the rules reject
fails before anything is downloaded, because finding out after an eight hour
fetch is not a useful time to find out.
"""
from __future__ import annotations

import json
import re
import shutil
from pathlib import Path

def known_suffixes() -> set[str]:
    """Every extension ingest can read, asked of ingest rather than listed here.

    A second copy of this list would drift from the real one the first time
    a format was added, and the symptom would be documents silently left out
    of the corpus. So there is no second copy.
    """
    from .corpus import DOC_TYPES, IMAGE_TYPES
    return DOC_TYPES | IMAGE_TYPES

# Below this many documents a compartment is reported as thin. It is not an
# error, because a small department is a real thing, but a stratum trained on
# two documents will not be worth serving and the operator should know.
THIN = 4


class PlanError(Exception):
    """The plan cannot be read, or says something that cannot be built."""


def _load_any(path: str) -> dict:
    """Read the plan whether it is YAML or JSON.

    JSON is accepted so that a plan can be generated by another system
    without that system needing a YAML library.
    """
    p = Path(path)
    if not p.exists():
        raise PlanError(
            f"No plan file at {path}.\n"
            f" - Run `stratum corpus plan init --out {path}` to get one to edit.")
    text = p.read_text(encoding="utf-8")
    if p.suffix.lower() in (".json",):
        try:
            return json.loads(text)
        except json.JSONDecodeError as e:
            raise PlanError(f"{path} is not valid JSON: {e}") from e
    try:
        import yaml
    except ImportError as e:
        raise PlanError(
            f"Reading {path} needs PyYAML. Either `pip install pyyaml`, or "
            f"write the plan as .json instead.") from e
    try:
        d = yaml.safe_load(text)
    except Exception as e:
        raise PlanError(f"{path} is not valid YAML: {e}") from e
    if not isinstance(d, dict):
        raise PlanError(
            f"{path} should be a mapping with a 'compartments' key at the top. "
            f"It read as {type(d).__name__}.")
    return d


def _as_list(value, where: str) -> list:
    """Accept a single string where a list is expected.

    People write `folders: raw/engineering` more often than they write the
    list form, and refusing that would be pedantry rather than safety.
    """
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    if isinstance(value, list):
        return value
    raise PlanError(f"{where} should be a list, or a single string. "
                    f"It is a {type(value).__name__}.")


def parse(path: str) -> dict:
    """Read a plan and check everything about it that can be checked on disk.

    Returns the normalised plan. Raises before any network traffic if the
    plan is wrong, because the whole point of a separate check step is that
    mistakes are cheap to find.
    """
    raw = _load_any(path)
    base = Path(path).resolve().parent

    comps_raw = raw.get("compartments")
    if not isinstance(comps_raw, dict) or not comps_raw:
        raise PlanError(
            "The plan needs a 'compartments' mapping, with one entry per "
            "department or project. See `stratum corpus plan init`.")

    compartments, problems = {}, []
    for name, body in comps_raw.items():
        if not isinstance(name, str) or not name.strip():
            problems.append(f"a compartment has a blank name")
            continue
        # A compartment name becomes a folder name under the output folder,
        # so it is checked as a path component and not merely as a label.
        # A name of '..' carries no forbidden character and would still walk
        # the build out of the folder it was told to write to, so the rule
        # is a positive one rather than a list of things to ban.
        if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_-]*", name):
            problems.append(
                f"compartment '{name}' is not usable as a folder name. Start "
                f"with a letter or digit, then letters, digits, dash and "
                f"underscore only.")
            continue
        if body is None:
            body = {}
        if not isinstance(body, dict):
            problems.append(f"compartment '{name}' should be a mapping of "
                            f"settings, not a {type(body).__name__}.")
            continue

        folders = _as_list(body.get("folders"), f"compartments.{name}.folders")
        urls = _as_list(body.get("urls"), f"compartments.{name}.urls")
        url_files = _as_list(body.get("url_files"),
                             f"compartments.{name}.url_files")

        for uf in url_files:
            p = (base / uf) if not Path(uf).is_absolute() else Path(uf)
            if not p.exists():
                problems.append(f"compartment '{name}' names a url file that "
                                f"does not exist: {uf}")
                continue
            for line in p.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if line and not line.startswith("#"):
                    urls.append(line)

        resolved = []
        for f in folders:
            p = (base / f) if not Path(f).is_absolute() else Path(f)
            if not p.exists():
                problems.append(f"compartment '{name}' names a folder that "
                                f"does not exist: {f}")
                continue
            if not p.is_dir():
                problems.append(f"compartment '{name}' names '{f}', which is "
                                f"a file rather than a folder.")
                continue
            resolved.append(p)

        bad = [u for u in urls if not u.lower().startswith(("http://", "https://"))]
        if bad:
            problems.append(f"compartment '{name}' has {len(bad)} entry that "
                            f"is not a web address, starting with {bad[0][:60]}")

        if not resolved and not urls:
            problems.append(
                f"compartment '{name}' has no material. Give it 'folders', "
                f"'urls' or 'url_files', or take it out of the plan.")

        compartments[name] = {
            "tier": body.get("tier", "restricted"),
            "family": body.get("family") or name,
            "description": body.get("description", ""),
            "volatile": bool(body.get("volatile", False)),
            "folders": resolved,
            "urls": urls,
        }

    prins_raw = raw.get("principals") or {}
    if not isinstance(prins_raw, dict):
        raise PlanError("'principals' should be a mapping of name to who they "
                        "may read.")
    principals = {}
    for name, body in prins_raw.items():
        if isinstance(body, list):
            body = {"reads": body}
        if not isinstance(body, dict):
            problems.append(f"principal '{name}' should be a list of "
                            f"compartments, or a mapping with a 'reads' list.")
            continue
        reads = _as_list(body.get("reads"), f"principals.{name}.reads")
        unknown = [c for c in reads if c not in compartments]
        if unknown:
            problems.append(
                f"principal '{name}' is granted compartments that the plan "
                f"does not define: {', '.join(unknown)}")
        principals[name] = {"reads": sorted(set(reads)),
                            "description": body.get("description", "")}

    if problems:
        raise PlanError("The plan has problems that have to be fixed first.\n"
                        + "\n".join(f" - {p}" for p in problems))

    families = {}
    for name, c in compartments.items():
        families.setdefault(c["family"], []).append(name)

    return {"path": str(Path(path).resolve()),
            "compartments": compartments,
            "principals": principals,
            "families": {k: sorted(v) for k, v in sorted(families.items())},
            "fetch": raw.get("fetch") or {}}


def policy_dict(plan: dict) -> dict:
    """The access policy the plan describes."""
    return {
        "compartments": [
            {"name": n, "tier": c["tier"], "volatile": c["volatile"],
             "description": c["description"]}
            for n, c in sorted(plan["compartments"].items())],
        "principals": [
            {"name": n, "compartments": p["reads"],
             "description": p["description"]}
            for n, p in sorted(plan["principals"].items())],
    }


def family_spec(plan: dict) -> dict:
    """The family grouping the plan declares."""
    return {"families": plan["families"]}


def check_policy(plan: dict) -> list[str]:
    """Run the plan's policy past the access rules and report what they say.

    The rules live in access.py and are the same ones every other command
    obeys. Checking here means a plan that would produce a policy nobody can
    load fails now rather than after the corpus is built.
    """
    from .access import AccessError, Policy
    try:
        Policy.from_dict(policy_dict(plan))
    except AccessError as e:
        return [str(e)]
    return []


def build(plan_path: str, out_dir: str, fetch: bool = True,
          pause: float = 0.0, verbose: bool = True) -> dict:
    """Lay out the corpus, the policy and the family spec from one plan.

    Local folders are copied rather than moved, so a mistake in the plan can
    never destroy the material it points at.
    """
    plan = parse(plan_path)
    complaints = check_policy(plan)
    if complaints:
        raise PlanError(
            "The plan describes an access policy the rules do not allow.\n"
            + "\n".join(f" - {c}" for c in complaints))

    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    pause = float(plan["fetch"].get("pause", pause) or 0.0)

    known = known_suffixes()
    report = {}
    left_out: dict[str, int] = {}
    for name, c in sorted(plan["compartments"].items()):
        dest = out / name
        dest.mkdir(parents=True, exist_ok=True)
        copied = skipped = 0

        for folder in c["folders"]:
            for src in sorted(folder.rglob("*")):
                if not src.is_file():
                    continue
                # Hidden files and the litter that sync clients leave behind
                # are not documents, and copying them only makes the corpus
                # look larger than it is.
                if any(p.startswith(".") or p.startswith("~$")
                       for p in src.relative_to(folder).parts):
                    continue
                if src.suffix.lower() not in known:
                    skipped += 1
                    left_out[src.suffix.lower() or "(no extension)"] = \
                        left_out.get(src.suffix.lower() or "(no extension)", 0) + 1
                    continue
                # Flattened with the sub path in the name, so two files
                # called report.pdf in different sub folders do not collide.
                rel = src.relative_to(folder)
                flat = "__".join(rel.parts)
                target = dest / flat
                if target.exists() and target.stat().st_size == src.stat().st_size:
                    continue
                shutil.copy2(src, target)
                copied += 1

        fetched = {"fetched": 0, "already": 0, "failed": 0}
        if c["urls"] and fetch:
            from .corpus import fetch_urls
            if verbose:
                print(f"\n{name}: {len(c['urls'])} web addresses")
            fetched = fetch_urls(c["urls"], str(dest), pause=pause,
                                 verbose=verbose)

        have = sum(1 for p in dest.iterdir() if p.is_file())
        report[name] = {"copied": copied, "skipped_type": skipped,
                        "documents": have, "family": c["family"],
                        "tier": c["tier"], **fetched}

    policy_path = out.parent / "policy.json"
    fam_path = out.parent / "families.json"
    policy_path.write_text(json.dumps(policy_dict(plan), indent=2) + "\n",
                           encoding="utf-8")
    fam_path.write_text(json.dumps(family_spec(plan), indent=2) + "\n",
                        encoding="utf-8")

    if verbose:
        print()
        print(f"Corpus laid out under {out}")
        print(f"  {'compartment':<18} {'family':<14} {'tier':<11} documents")
        thin = []
        for name, r in report.items():
            flag = ""
            if r["documents"] < THIN:
                flag = "   thin"
                thin.append(name)
            print(f"  {name:<18} {r['family']:<14} {r['tier']:<11} "
                  f"{r['documents']:>4}{flag}")
        total = sum(r["documents"] for r in report.values())
        failed = sum(r.get("failed", 0) for r in report.values())
        print(f"  {'':<18} {'':<14} {'':<11} {total:>4} in total")
        print()
        print(f"Access policy  -> {policy_path}")
        print(f"Family spec    -> {fam_path}")
        if failed:
            print(f"\n{failed} download(s) failed. Re-run the same command, "
                  f"files already present are kept.")
        if left_out:
            # Said out loud, because a company share drive is full of formats
            # nobody thought about, and a quiet skip reads as coverage that
            # was never there.
            order = sorted(left_out.items(), key=lambda kv: -kv[1])
            print(f"\nLeft out, no extractor for these formats")
            for ext, n in order[:8]:
                print(f"  {ext:<14} {n:>5} file(s)")
            if len(order) > 8:
                print(f"  and {len(order) - 8} other format(s)")
            print(" Convert them, or say so and an extractor can be added. "
                  "Images need `--images` at ingest or they are skipped too.")
        if thin:
            print(f"\nThin compartments, fewer than {THIN} documents each: "
                  f"{', '.join(thin)}")
            print(" A stratum trained on this little will not be worth "
                  "serving. Give them more material, or fold them into a "
                  "neighbouring compartment.")
        print()
        print("Next")
        print(f"  stratum corpus ingest --in {out} --out chunks.jsonl "
              f"--compartments")
        print(f"  stratum access check --policy {policy_path}")

    return {"plan": plan, "report": report,
            "policy": str(policy_path), "families": str(fam_path)}


EXAMPLE = """\
# Which compartments exist, what material feeds each one, and which cluster
# it belongs to. `stratum corpus plan build` reads this and produces the
# folder layout, the access policy and the family spec together.
#
# tier says where the material is allowed to live.
#   company     everyone can read it, so it may go into shared weights
#   department  a group can read it, so it gets its own adapter
#   restricted  index only, it never enters any weights
#
# family says which cluster the compartment joins. Compartments that write
# alike share one adapter, which is what keeps the adapter count per person
# inside the limit of about three that merging can survive.
#
# Two rules the checker will hold you to, because both are the difference
# between an access control and the appearance of one.
#
#   company tier has to be readable by every principal. It goes into shared
#   weights, and a weight cannot be filtered afterwards.
#
#   department tier needs at least two principals. A compartment one person
#   reads is that person's material, and training a shared adapter on it
#   puts it inside a model other people load. Use restricted instead.

compartments:

  public:
    tier: company
    family: general
    description: Everyone reads this, so it can go into shared weights
    folders: [raw/public]

  engineering:
    tier: department
    family: technical
    description: Rotating equipment and process plant
    folders: [raw/engineering]

  maintenance:
    tier: department
    family: technical
    description: Inspection, repair and reliability
    folders: [raw/maintenance]

  # Material can also come straight off the web. Both can be used together,
  # and url_files points at a text file with one address per line.
  standards:
    tier: department
    family: technical
    description: Reference standards the engineers work to
    urls:
      - https://en.wikipedia.org/api/rest_v1/page/html/ISO_9000_family

  legal:
    tier: department
    family: commercial
    description: Contracts and disputes
    folders: [raw/legal]

  # Pay data changes weekly, so it must never be trained into anything.
  # Restricted material is still searched and still answered from, by the
  # people cleared for it. It just stays out of every weight, which is what
  # lets it be corrected or deleted the moment the source changes.
  payroll:
    tier: restricted
    family: people
    volatile: true
    description: Changes weekly, index only
    folders: [raw/payroll]

# Who may read what. Everything a person can read is searchable by them.
# Only the company and department tiers become adapters.
principals:

  plant_engineer:
    reads: [public, engineering, maintenance, standards]

  reliability_engineer:
    reads: [public, engineering, maintenance, standards]

  counsel:
    reads: [public, legal]

  finance_lead:
    reads: [public, legal, payroll]

  contractor:
    description: Outside the company, sees only what everyone sees
    reads: [public]

# Optional. A pause between downloads, in seconds. Public sites refuse a
# fast run and answer with 429, which loses most of the download while still
# looking like it worked. Nothing to do with a corpus off your own share
# drive, where there is no rate limit to trip.
fetch:
  pause: 0.5
"""


def write_example(path: str) -> None:
    p = Path(path)
    if p.exists():
        raise PlanError(f"{path} already exists. Move it aside first, so an "
                        f"edited plan is never overwritten.")
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(EXAMPLE, encoding="utf-8")
    print(f"Example plan -> {path}")
    print()
    print("Edit it so the compartments are your departments and the folders")
    print("point at your material, then")
    print(f"  stratum corpus plan check --plan {path}")
    print(f"  stratum corpus plan build --plan {path} --out corpus")
